// Regenerated by scripts/write-build-date.ts immediately before every
// `expo run:ios --configuration Release` build — see certExpiry.ts, which
// uses this to know when the free Apple ID signing certificate expires
// (~7 days after the build/signing date).
export const BUILD_DATE = '2026-08-01T09:06:26.962Z';
