/**
 * Stamps src/lib/buildInfo.ts with the current time — run automatically
 * before every Release build (see `npm run release:ios`) so the app knows
 * when its free Apple ID signing certificate will expire (~7 days later).
 *
 * Usage: tsx scripts/write-build-date.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const buildDate = new Date().toISOString();

const content = `// Regenerated by scripts/write-build-date.ts immediately before every
// \`expo run:ios --configuration Release\` build — see certExpiry.ts, which
// uses this to know when the free Apple ID signing certificate expires
// (~7 days after the build/signing date).
export const BUILD_DATE = '${buildDate}';
`;

writeFileSync(join(__dirname, '../src/lib/buildInfo.ts'), content);
console.log(`Wrote BUILD_DATE = ${buildDate}`);
